### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by YinggangLee** [johnsonmoon/ShellExecutor#1]
您好，我目前做的项目需要一个Java调用Shell脚本的功能，看了您的项目大受启发。
但是我之前再看文档的时候注意到一个细节问题，就是如果传入的命令带参数，或者被空格分成几部分，比如“java -version”，在传入参数的时候需要将这个字符串分成两部分，组成一个String[]，即new String["java","-version"],才能正确执行。
所以推荐将execute方法的第一个参数改成String[]，以适用更多的情景。

**Comment by johnsonmoon** [comment]
多谢指正。现已修复带参数命令的执行问题。并进行增强，支持管道、重定向等复杂命令的执行。
